<?php
// src/JFC/ModelBundle/Repository/PostRepository.php

namespace JFC\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findPosts()
    {
        return $this->findBy(array(), array('createdAt' => 'DESC'));
    }

    public function findPostsBySlug($slug)
    {
        return $this->createQueryBuilder('post')
            ->select('post')
            ->where('post.slug = :slug')
            ->setParameter('slug', $slug)
            ->orderBy('post.createdAt', 'DESC')
            ->getQuery()
            ->getSingleResult();

//        return $this->findOneBy(array(
//            'slug' => $slug
//        ), array(
//            'createdAt' => 'DESC'
//        ));
    }

    public function getBlogsByCategory($category)
    {
        return $this->createQueryBuilder('post')
            ->leftJoin('post.category','category')
            ->andWhere('category.title = :category')
            ->setParameter('category', $category)
            ->orderBy('post.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
