<?php
// src/JFC/ModelBundle/Repository/ReplyRepository.php

namespace JFC\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReplyRepository extends EntityRepository
{

}
