security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        JFC\ModelBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        our_database_users:
            entity: { class: JFCModelBundle:User, property: username }

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /
            anonymous: ~
            remember_me:
                key: Blue Horseshoe loves Anacott Steel
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
         - { path: ^/post , roles: ROLE_USER }
